apiVersion: v1
kind: Namespace
metadata:
  name: xone-production
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
---
apiVersion: v1
kind: Namespace
metadata:
  name: fluentd
---
apiVersion: v1
kind: Namespace
metadata:
  name: vpa

